"""add_cascade_delete_for_hotel_images

Revision ID: 144986d6905a
Revises: 7b6f7f89874b
Create Date: 2025-08-04 13:04:39.976208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "144986d6905a"
down_revision: Union[str, Sequence[str], None] = "7b6f7f89874b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("hotel_images_hotel_id_fkey"), "hotel_images", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "hotel_images", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("room_images_room_id_fkey"), "room_images", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "room_images", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "room_images", type_="foreignkey")
    op.create_foreign_key(
        op.f("room_images_room_id_fkey"), "room_images", "rooms", ["room_id"], ["id"]
    )
    op.drop_constraint(None, "hotel_images", type_="foreignkey")
    op.create_foreign_key(
        op.f("hotel_images_hotel_id_fkey"),
        "hotel_images",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    # ### end Alembic commands ###
