"""Edit hotels and rooms models, add images

Revision ID: 1acd1597fc5a
Revises: 8351d44d7ed3
Create Date: 2025-07-30 15:42:43.515225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1acd1597fc5a"
down_revision: Union[str, Sequence[str], None] = "8351d44d7ed3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotel_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "room_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("hotels", "image_id")
    op.drop_column("rooms", "image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms", sa.Column("image_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "hotels",
        sa.Column("image_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("room_images")
    op.drop_table("hotel_images")
    # ### end Alembic commands ###
