"""add relationship

Revision ID: 4c4d3ea0885b
Revises: 144986d6905a
Create Date: 2025-08-04 17:42:28.017855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c4d3ea0885b"
down_revision: Union[str, Sequence[str], None] = "144986d6905a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hotels", "rooms_quantity", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hotels", "rooms_quantity", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
