"""Edit hotels and rooms models, add images

Revision ID: 7b6f7f89874b
Revises: 1acd1597fc5a
Create Date: 2025-07-30 15:47:02.545736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b6f7f89874b"
down_revision: Union[str, Sequence[str], None] = "1acd1597fc5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
